spring:
  config:
    import: optional:classpath:database-prod.properties
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  jpa:
    open-in-view: true  # 뷰 렌더링 중 지연 로딩 허용 (명시적 설정)
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB106Dialect
  flyway:
    enabled: true
    locations: classpath:db/migration
  datasource:
    hikari:
      # 운영환경 커넥션 풀 설정 (더 보수적)
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
      # 하우스키퍼 설정 (운영환경에서 더 자주 체크)
      housekeeping-period-ms: 15000  # 15초마다 체크
      # 운영환경 추가 설정
      validation-timeout: 5000
      register-mbeans: true

server:
  port: 8080

app:
  file-storage:
    location: /opt/cmms11/storage/uploads
    max-size: 10485760  # 운영환경에서는 10MB로 제한 (multipart는 100MB)
    allowed-extensions: jpg,jpeg,png,pdf,doc,docx,xls,xlsx,hwp,hwpx,zip  # 운영환경에서는 txt 제거로 보안 강화

aws:
  s3:
    bucket-name: ${AWS_S3_BUCKET:prodYULSLAB-bucket}
    versioning: true
    preserve-original-filename: true
    max-size: 10485760
    allowed-extensions: jpg,jpeg,png,pdf,doc,docx,xls,xlsx,hwp,hwpx,zip,txt

logging:
  level:
    com.cmms11: INFO
    org.springframework.web: WARN
    com.zaxxer.hikari: WARN  # 운영환경에서는 경고만 로깅
    org.springframework.jdbc: WARN  # JDBC 경고만 로깅
  file:
    name: /opt/cmms11/logs/cmms11.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
