spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/cmms11?useUnicode=true&characterEncoding=utf8
    username: cmms11_dev
    password: cmms
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB106Dialect
  flyway:
    enabled: false

server:
  port: 8080

app:
  file-storage:
    location: storage/uploads
    max-size: 10485760
    allowed-extensions: jpg,jpeg,png,pdf,txt
