spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB106Dialect
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

app:
  file-storage:
    location: /opt/cmms11/storage/uploads
    max-size: 10485760
    allowed-extensions: jpg,jpeg,png,pdf,doc,docx,xls,xlsx,hwp,hwpx,zip,txt

aws:
  s3:
    bucket-name: ${AWS_S3_BUCKET:prodYULSLAB-bucket}
    versioning: true
    preserve-original-filename: true
    max-size: 10485760
    allowed-extensions: jpg,jpeg,png,pdf,doc,docx,xls,xlsx,hwp,hwpx,zip,txt

logging:
  level:
    com.cmms11: INFO
    org.springframework.web: WARN
  file:
    name: /opt/cmms11/logs/cmms11.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
