spring:
  config:
    import: optional:classpath:database-dev.properties
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB106Dialect
  flyway:
    enabled: false
  datasource:
    hikari:
      # 커넥션 풀 설정
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
      # 하우스키퍼 설정
      housekeeping-period-ms: 30000  # 30초마다 체크

server:
  port: 8080

app:
  file-storage:
    location: storage/uploads
    max-size: 20971520  # 개발환경에서는 20MB 허용
    allowed-extensions: jpg,jpeg,png,pdf,doc,docx,xls,xlsx,hwp,hwpx,zip,txt,gif,bmp,mp4,mov  # 개발환경에서는 더 많은 형식 허용

aws:
  s3:
    bucket-name: devYULSLAB-bucket
    versioning: false
    preserve-original-filename: true
    max-size: 10485760
    allowed-extensions: jpg,jpeg,png,pdf,doc,docx,xls,xlsx,hwp,hwpx,zip,txt

logging:
  level:
    com.cmms11: INFO
    com.zaxxer.hikari: DEBUG  # HikariCP 상세 로그
    org.springframework.jdbc: DEBUG  # JDBC 로그
