spring:
  config:
    import:
      - optional:classpath:database-dev.properties
      - optional:classpath:storage-dev.properties
      - optional:classpath:webhook-dev.properties
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  jpa:
    open-in-view: true  # 뷰 렌더링 중 지연 로딩 허용 (명시적 설정)
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false
  datasource:
    hikari:
      # 커넥션 풀 설정
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
      # 하우스키퍼 설정
      housekeeping-period-ms: 30000  # 30초마다 체크

server:
  port: 8080

app:
  approval:
    base-url: http://localhost:8080

logging:
  level:
    com.cmms11: INFO
    com.zaxxer.hikari: INFO  # HikariCP 상세 로그
    org.springframework.jdbc: INFO  # JDBC 로그
  file:
    name: /opt/cmms11/logs/cmms11-dev.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
